### ISSUE TITLE
Bundle/Minify compiled files on build

### ISSUE THREAD

**Issue by ianschmitz** [madskristensen/BundlerMinifier#28]
Working with typescript can be troublesome as the extension doesn't pick up changes to the compiled .js files, which means the bundled/minified file is not updated.

**Comment by zecompadre** [comment]
any update ?

**Comment by cjmagee** [comment]
This is the same for LESS, it appears. The bundling/minification does not happen when the css file is compiled by the Web Compiler plugin (also mads)

**Comment by madskristensen** [comment]
No update on this yet. Got a lot of things and extensions to work on at the moment. I'll get to it...

**Comment by cjmagee** [comment]
I forked and implemented the FileSystemWatcher. Mind taking a look?

**Comment by madskristensen** [comment]
It looks pretty good!! One concern is error handling with _node_modules_ folder for instance. It can throw `PathTooLongException` from a file system watcher. Also, when installing Bower or npm packages in a project then there will be a lot of files written to disk - hundreds of files can be added pretty rapidly. Does it handle that scenario too?

**Comment by cjmagee** [comment]
I will look into the node modules exclusion.

In the Bundle Processor method, you'll see that it disables raising events until the bundle processing has finished. The most process methods called at any one time would be equal to the amount of projects in the solution.

**Comment by cjmagee** [comment]
I did some more testing and added a few lines to exclude a relative path of "node_modules". It also appears that the PathTooLongException isn't thrown by the file watcher, it appears to recognize the file was changed at a path too long for the watcher and shorten the file names.

"NODE_M~1/SOME_L~1/NODE_M~1/SOME_L~1/NODE_M~1/backbone/NODE_M~1/UNDERS~1/underscore.css"

Should be clear on those two fronts.

**Comment by madskristensen** [comment]
@cjmagee, wouldn't it make sense to have a single `FileSystemWatcher` for each project in the solution that contains a `compilerconfig.json` file?

**Comment by cjmagee** [comment]
I couldn't decide. I wanted to use a single watcher, but since FileSystemWatcher has a restriction to filter by 1 file extension per watcher (http://stackoverflow.com/questions/6965184/how-to-set-filter-for-filesystemwatcher-for-multiple-file-types), the watcher would be raising events for every single file extension (most of which we are not watching) and then filtering out at event time. I could a single watcher being poorer performance-wise in cases like you mentioned above with nuget packages creating hundreds of files in seconds compared to 1-2 watchers raising events for specific extensions.

**Comment by madskristensen** [comment]
Perhaps @BillHiebert has an idea on how to watch files best? I know there is a file system watcher service in VS we should probably use as well, but I have not been able to find any documentation on it

**Comment by BillHiebert** [comment]
Yes. VS has a file change service which can be used for this. See https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsfilechangeex.aspx

**Comment by cjmagee** [comment]
Thanks @BillHiebert. I'll make these changes tonight @madskristensen.

**Comment by brunis** [comment]
I have this issue aswell, when we make changes to .less files, .css files are correctly generated, but bundles are not updated appropriately afterwards.

**Comment by cjmagee** [comment]
@madskristensen Mind checking out the branch again? I've implemented IVsFileChangeEx.

**Comment by madskristensen** [comment]
@cjmagee You still have the FileListeners implemented. Should they not be removed after the change to `IVsFileChangeEx`?

**Comment by cjmagee** [comment]
@madskristensen Sorry, I don't see this. Can you clarify? The IVsFileChangeEx has you subscribe to changes within a directory or specific files. Unfortunately being advised on directory change did not appear to give any information regarding the file changed, just the directory changed, which is why I had to add specific "AdviseFileChange" for source files.

**Comment by cjmagee** [comment]
@madskristensen To clarify, if I were to register "AdviseDirectoryChange" for the project root (/), and I changed the file /Styles/style.css, it would fire a directory change for "/Styles/" (No absolute path). There was no reliable way to get the related project from the path for us to rebuild the bundles for that project.

By registering each file change individually, you can specifically search for the file changed as a project item to get the related project, and related bundles.

**Comment by cjmagee** [comment]
@madskristensen I was under the impression we wanted to maintain the references returned from "AdviseFileChange" on the FIleChangeEx service in order to remove them if the bundle configuration files are changed. I didn't want to start leaving listeners for files removed from bundles.

**Comment by madskristensen** [comment]
Not sure I follow. So the IVsFileChangeEx listens for file changes and that is then used to implement FileSystemWatchers? Isnt' that redundant?

**Comment by cjmagee** [comment]
I'm not sure where you're still seeing file system watchers. I can't see that in my branch at all. 

Chris

**Comment by madskristensen** [comment]
Oh, i must have looked at old code or something. My bad

**Comment by cveld** [comment]
any update?

**Comment by madskristensen** [comment]
Fixed in latest CI build
