### ISSUE TITLE
Stack is empty, fails to minify

### ISSUE THREAD

**Issue by OrbintSoft** [madskristensen/BundlerMinifier#391]
### Installed product versions
- Visual Studio 2017 15.9.3032
- This extension: 2.8.391

### Description
The extension fails to minify javascript files, the error is: "Stack is empty"

### Steps to recreate
Download poppler.js 1.14.3, you can install from library manager

### Current behavior
An error is generated ("Stack is empty") and poppler.js, is not minified, no output is generated.

### Expected behavior
The file should be minified without problems, a poppler.min.js should be generated

**Comment by Raystorm7** [comment]
Same with version 2.8.396.

**Comment by CrestApps** [comment]
I have the same problem. I think the problem happens when `map` function is used

**Comment by Gavvers** [comment]
I'm getting the same problem on Visual Studio 2019 16.2.4 and BundlerMinifier 2.8.396.

It seems like arrow functions were supposed to have been fixed a while ago according to #277 , but ... apparently not??

**Comment by babibn** [comment]
I'm Getting same Error 
The Problem is Related to  (x)=>x.something

.map(x => x.Fields.BasePrice.StringValue);

**Comment by valeriob** [comment]
Same problem on BundlerMinifier 2.8.396

**Comment by SteinTheRuler** [comment]
Same problem here with Visual Studio Community 2019 v. 16.4.0 - extension v. 2.8.396

**Comment by RedBirdOBX** [comment]
Same here.  VS 2019 Pro.  Web Essentials. v0.5.7

**Comment by stap123** [comment]
Same problem here, can confirm it's the "=>" syntax. Once I removed the occurrences it works as expected.

**Comment by lauchacarro** [comment]
BundlerMinifier only supports ES5.
I recommend you use https://babeljs.io/ to convert your javascript scripts to ES5 and replace the contents of your JS files

I tell you this because I see that you use ES6 features

**Comment by ghhv** [comment]
FYI, as of today, BundleMinifier 3.2.435 is supporting `=>` for me.. 

but it fails when the source map is enabled (if the file has `=>`) with the Stack Empty error...

So turn off sourcemap.. no problem..

**Comment by RedBirdOBX** [comment]
> FYI, as of today, BundleMinifier 3.2.435 is supporting `=>` for me..
> 
> but it fails when the source map is enabled (if the file has `=>`) with the Stack Empty error...
> 
> So turn off sourcemap.. no problem..

The latest version is  2.8.396 as of this post so where do you see 3.2.x... ?

Thanks!

**Comment by SteinTheRuler** [comment]
> 
> 
> BundlerMinifier only supports ES5.
> I recommend you use https://babeljs.io/ to convert your javascript scripts to ES5 and replace the contents of your JS files
> 
> I tell you this because I see that you use ES6 features

why shouldn't I use ES6 features?

I've had nothing but problems when converting to other versions

**Comment by jtsom** [comment]
Any chance this is going to be addressed? Use use source maps and I had to remove all instances of the arrow functions in my code to get around this problem. Not using ES6 doesn't seem a viable solution...

**Comment by SteinTheRuler** [comment]
is this extension still being developed? the arrow function issues should be fixed soon

**Comment by SteinTheRuler** [comment]
when defining custom @font-faces the compiled src is relative to the build folder. I have the font files in the same folder as the SCSSS files, but when compiled I get "src: url("../../STYLE/Layout/Poppins-Medium.ttf"); }"

**Comment by jtsom** [comment]
Over two years and this is still a problem. Any chance it will ever get fixed?

**Comment by jtsom** [comment]
Someone want to poke @madskristensen  - this is now causing our Azure Devops to fail

**Comment by Gavvers** [comment]
> 
> 
> Over two years and this is still a problem. Any chance it will ever get fixed?

In my amateur experience, by now it would be up to the rest of the community to fork this and fix it. I am no longer working on the project that used this, so I am not motivated, myself.

**Comment by jtsom** [comment]
> > Over two years and this is still a problem. Any chance it will ever get fixed?
> 
> In my amateur experience, by now it would be up to the rest of the community to fork this and fix it. I am no longer working on the project that used this, so I am not motivated, myself.

We should we? This is the recommended solution, per Microsoft's documentation, to add bundling and minification to a Visual Studio project. If they aren't going to support it, then it should be either removed, or another solution added to VS. it's clear the author is just ignoring this issue.

**Comment by jtsom** [comment]
@madskristensen Are you ever going to weigh in on this issue, on your project? This is causing Azure Devops deploys that depend on this package to fail. Or are you washed your hands of this package?

Perhaps Microsoft should assign this to someone who has an interest in fixing it.
